(ns template.default
  (:require [template.tailwind :refer [nav-a]]))


(defn template [& {:keys [embed title]}]
  [:html {:lang "en"}
   [:head
    [:meta {:charset "utf-8"}]
    ; viewport settings for responsive design
    [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
    ; SEO related setting
    "\n$if(tags)$\n"
    [:meta {:name "keywords" :content "$tags$"}]
    "\n$endif$\n"
    "$if(summary)$\n"
    [:meta {:name "description" :content "$summary$"}]
    "\n$endif$\n"
    [:title "Put some ink into the inkpot - " (if title title "$title$")]
    ;atom.xml
    [:link {:href "atom.xml" :type "application/atom+xml" :rel "alternate" :title "Put some ink into the inkpot"}]
    [:link {:rel "stylesheet" :href "/css/output.css"}]
    [:link {:rel "stylesheet" :href "/css/default.css"}]
    [:link {:rel "stylesheet" :href "/css/table.css"}]
    [:link {:rel "stylesheet" :href "/css/hightlight.css"}]]
   [:body  {:class "text-base text-black"}
    [:header {:class "border-b-2 border-black"}
     [:div.logo
      [:a {:href "/"} "Put some ink into the inkpot"]]
     [:nav {:class "text-right"}
      [:a {:href "/archive.html" :class (nav-a)} "Archive"]
      [:a {:href "/atom.xml" :class (nav-a)} "RSS"]]]
    [:main
     (if embed embed "$body$")]
    [:footer {:class "mt-12 py-3 border-t-2 border-black text-sm text-gray-500"}
     "Site generated by pandoc and babashka"]]])